@apiurl = http://localhost:8080/funcionario

###
GET  {{apiurl}}/todos

###
GET  {{apiurl}}/exame/?exame=Audiometria

###
POST {{apiurl}}/salvar
Content-Type: application/json

  {
    "matricula":"812548",
    "nome":"Alisson",
	"cliente":{
		"cnpj":"10052002",
		"nomeFantasia":"Total Life",
		"endereco":"Rua Zero",
		"telefone":"48844848"	
	},
	"exame":{
		"nomeExame":"Audiometria",
		"dataAgendado":"10/02/2022"	
	}
}


###
DELETE {{apiurl}}/livros/10

###
PUT  {{apiurl}}/salvar
Content-Type: application/json

{
    "matricula":"0002",
    "nome":"Aline"
}

###
POST {{apiurl}}/salvar
Content-Type: application/json

  {
    "matricula":"812548",
    "nome":"Alisson",
	"cliente":{
		"cnpj":"10052002",
		"nomeFantasia":"Total Life",
		"endereco":"Rua Zero",
		"telefone":"48844848"	
	}
}

###
POST {{apiurl}}/salvar
Content-Type: application/json

{
    "matricula":"812548",
    "nome":"Alisson",
	"cliente":{
		"cnpj":"10052002",
		"nomeFantasia":"Total Life",
		"endereco":"Rua Zero",
		"telefone":"48844848"	
	},
		"prestador":{
			"nome":"Maxipas",
			"razao":"Total Life",
			"tipo":"Pessoa Juridica",
			"email":"alisson@gmail.com",
			"obs":"Resultado disponivel no Portal"	
		},
		"exame":{
			"nomeExame":"Audiometria",
			"dataAgendado":"10/02/2022",	
			"tipo":{
			"tipo":"PER"
		},
		"resultado":{
			"aso":"pendente",
			"fco":"pendente",
			"guia":"pendente",
			"tudoOk":"pendente"
		}
	}
}
